version: '3.5'

services:
  bot:
    image: hlystovea/reservoirs_bot:latest
    container_name: bot
    restart: always
    command: python3 bot.py
    env_file:
      - ./.env

networks:
  default:
    name: reservoirs_network
    driver: bridge
