version: '3.3'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  crawler:
    image: hlystovea/reservoirs_bot:latest
    container_name: crawler
    restart: always
    command: python3 crawler.py
    depends_on:
      - db
    env_file:
      - ./.env
  bot:
    image: hlystovea/reservoirs_bot:latest
    container_name: bot
    restart: always
    command: python3 main.py
    depends_on:
      - db
    env_file:
      - ./.env
  web:
    build: ./web
    container_name: web
    restart: always
    command: gunicorn web.wsgi --bind 0.0.0.0:8000
    volumes:
      - static_value:/resource_planner/static/
      - media_value:/resource_planner/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    container_name: reservoirs_nginx
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  postgres:
  static_value:
  media_value: