version: '3.3'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  crawler:
    image: hlystovea/reservoirs_bot:latest
    container_name: crawler
    restart: always
    command: python3 crawler.py
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres:
